name: Reusable Test Workflow
on:
  workflow_call:

jobs:
  test:
    name: Run test-suite.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source.
        uses: actions/checkout@v3
      - name: Setup rust toolchain.
        run: rustup show
      - name: Restore cargo cache.
        uses: Swatinem/rust-cache@v1
      - name: Compile test binary.
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --no-run --workspace --verbose
      - name: Run tests.
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --verbose
